package uz.pdp.enumerators;

public enum UserRole {
    MAIN_DOCTOR,
    ADMINISTRATOR,
    THERAPIST,
    PEDIATRICIAN,
    OTOLARYNGOLOGY,
    CARDIOLOGIST,
    RHEUMATOLOGIST,
    ENDOCRINOLOGIST,
    ANESTHESIOLOGIST,
    DENTIST,
    GENERAL_PRACTITIONER,
    NEUROLOGIST,
    GASTROENTEROLOGIST,
    ALLERGIST,
    SURGEON,
    PATIENT
}
